### ISSUE TITLE
rake spec aborted

### ISSUE THREAD

**Issue by ujihisa** [jugyo/termtter#110]
```
(in /Users/ujihisa/git/termtter)
** Invoke spec (first_time)
** Execute spec
F*..............................FFF...............*F..................Username: test
.......
   [36m<(@)//_[0m  .  .      [41m Termtter [4m1.6.0[0m[41m [0m
      [36m\\[0m           [41m http://termtter.org/ [0m

.
   [36m<(@)//_[0m  .  .      [41m Termtter [4m1.6.0[0m[41m [0m
      [36m\\[0m           [41m http://termtter.org/ [0m

.
   [36m<(@)//_[0m  .  .      [41m Termtter [4m1.6.0[0m[41m [0m
      [36m\\[0m           [41m http://termtter.org/ [0m

............................................................................................................................*.....F................

Pending:

standard_commands needs more specs! (Not Yet Implemented)
./spec/plugins/channel_spec.rb:26

standard_commands needs more specs! (Not Yet Implemented)
./spec/plugins/standard_commands_spec.rb:25

Extensions for Windows needs spec (Not Yet Implemented)
./spec/termtter/system_extensions/windows_spec.rb:7

1)
NoMethodError in 'Termtter::Client returns registerd commands'
undefined method `name' for nil:NilClass
./spec/plugins/channel_spec.rb:19:
./spec/plugins/channel_spec.rb:11:in `each'
./spec/plugins/channel_spec.rb:11:

2)
NoMethodError in 'Termtter::Client when the plugin footer is loaded should add footer at update'
undefined method `call_commands' for Termtter::Client:Module
./spec/plugins/footer_spec.rb:28:

3)
NoMethodError in 'Termtter::Client when the plugin footer is loaded should call footer command to change config.footer'
undefined method `call_commands' for Termtter::Client:Module
./spec/plugins/footer_spec.rb:34:

4)
NoMethodError in 'Termtter::Client when the plugin footer is loaded should call footer no argument to set config.footer to nil'
undefined method `call_commands' for Termtter::Client:Module
./spec/plugins/footer_spec.rb:42:

5)
NameError in 'sqlite3 update should not return false'
undefined local variable or method `status' for #<Termtter::Storage::SQLite3:0x19ae060>
./spec/plugins/storage/sqlite3_spec.rb:26:

6)
Spec::Mocks::MockExpectationError in 'Termtter can open browser that suites platform'
#<Spec::Example::ExampleGroup::Subclass_36:0x1b04f54> received :system with unexpected arguments
  expected: ("firefox", "example.com")
       got: ("start", "example.com")
./spec/termtter/system_extensions_spec.rb:58:
./spec/termtter/system_extensions_spec.rb:49:in `each'
./spec/termtter/system_extensions_spec.rb:49:
./spec/spec_helper.rb:18:in `be_quiet'
./spec/termtter/system_extensions_spec.rb:46:

Finished in 4.29123 seconds

226 examples, 6 failures, 3 pending
rake aborted!
Command /opt/local/bin/ruby -I"lib"  "/Users/ujihisa/.gem/ruby/1.8/gems/rspec-1.2.9/bin/spec" "spec/plugins/channel_spec.rb" "spec/plugins/cool_spec.rb" "spec/plugins/curry_spec.rb" "spec/plugins/db_spec.rb" "spec/plugins/defaults/hashtag_spec.rb" "spec/plugins/defaults/list_spec.rb" "spec/plugins/defaults/retweet_spec.rb" "spec/plugins/draft_spec.rb" "spec/plugins/expand-tinyurl_spec.rb" "spec/plugins/fib_spec.rb" "spec/plugins/footer_spec.rb" "spec/plugins/gsub_spec.rb" "spec/plugins/haml_spec.rb" "spec/plugins/md5pass_spec.rb" "spec/plugins/pause_spec.rb" "spec/plugins/shell_spec.rb" "spec/plugins/spam_spec.rb" "spec/plugins/standard_commands_spec.rb" "spec/plugins/storage/sqlite3_spec.rb" "spec/plugins/truncate_spec.rb" "spec/termtter/active_rubytter_spec.rb" "spec/termtter/api_spec.rb" "spec/termtter/client_spec.rb" "spec/termtter/command_spec.rb" "spec/termtter/config_setup_spec.rb" "spec/termtter/config_spec.rb" "spec/termtter/hook_spec.rb" "spec/termtter/hookable_spec.rb" "spec/termtter/memory_cache_spec.rb" "spec/termtter/optparse_spec.rb" "spec/termtter/rubytter_proxy_spec.rb" "spec/termtter/system_extensions/windows_spec.rb" "spec/termtter/system_extensions_spec.rb" "spec/termtter/task_manager_spec.rb" "spec/termtter/task_spec.rb" "spec/termtter_spec.rb" -c failed
/Users/ujihisa/.gem/ruby/1.8/gems/rspec-1.2.9/lib/spec/rake/spectask.rb:177:in `define'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:1112:in `verbose'
/Users/ujihisa/.gem/ruby/1.8/gems/rspec-1.2.9/lib/spec/rake/spectask.rb:153:in `define'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/opt/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Users/ujihisa/.gem/ruby/1.8/gems/rake-0.8.7/bin/rake:31
/Users/ujihisa/.gem/ruby/1.8/bin/rake:19:in `load'
/Users/ujihisa/.gem/ruby/1.8/bin/rake:19
```

**Comment by jugyo** [comment]
NameError in 'sqlite3 update should not return false' 以外はなおってるはず
